//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiCo.Utilities.I18n {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Billing {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Billing() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiCo.Utilities.I18n.Billing", typeof(Billing).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amounts.
        /// </summary>
        public static string amounts {
            get {
                return ResourceManager.GetString("amounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string balance {
            get {
                return ResourceManager.GetString("balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Available.
        /// </summary>
        public static string balance_available {
            get {
                return ResourceManager.GetString("balance_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check balance.
        /// </summary>
        public static string balance_check {
            get {
                return ResourceManager.GetString("balance_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A notice will be sent to you in case your balance drops below this value..
        /// </summary>
        public static string balance_limit_desc {
            get {
                return ResourceManager.GetString("balance_limit_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Balance Low Warning.
        /// </summary>
        public static string balance_limit_send {
            get {
                return ResourceManager.GetString("balance_limit_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated balance low warning limit.
        /// </summary>
        public static string balance_limit_update_success {
            get {
                return ResourceManager.GetString("balance_limit_update_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance low value.
        /// </summary>
        public static string balance_limit_value {
            get {
                return ResourceManager.GetString("balance_limit_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative Limit.
        /// </summary>
        public static string balance_negative_limit {
            get {
                return ResourceManager.GetString("balance_negative_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated balance negative limit.
        /// </summary>
        public static string balance_negative_limit_update_success {
            get {
                return ResourceManager.GetString("balance_negative_limit_update_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No balance available.
        /// </summary>
        public static string balance_no {
            get {
                return ResourceManager.GetString("balance_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Transaction.
        /// </summary>
        public static string balance_transaction {
            get {
                return ResourceManager.GetString("balance_transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to cancel this transaction?.
        /// </summary>
        public static string balance_transaction_cancell_ask {
            get {
                return ResourceManager.GetString("balance_transaction_cancell_ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to reactivate this transaction?.
        /// </summary>
        public static string balance_transaction_cancell_revert_ask {
            get {
                return ResourceManager.GetString("balance_transaction_cancell_revert_ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Transaction already exists..
        /// </summary>
        public static string balance_transaction_exists {
            get {
                return ResourceManager.GetString("balance_transaction_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge History.
        /// </summary>
        public static string balance_transactions {
            get {
                return ResourceManager.GetString("balance_transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance has been updated.
        /// </summary>
        public static string balance_updated_success {
            get {
                return ResourceManager.GetString("balance_updated_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string bank {
            get {
                return ResourceManager.GetString("bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank account.
        /// </summary>
        public static string bank_account {
            get {
                return ResourceManager.GetString("bank_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank accounts.
        /// </summary>
        public static string bank_accounts {
            get {
                return ResourceManager.GetString("bank_accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIC.
        /// </summary>
        public static string bic {
            get {
                return ResourceManager.GetString("bic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill ID.
        /// </summary>
        public static string bill_id {
            get {
                return ResourceManager.GetString("bill_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billed On.
        /// </summary>
        public static string billed_on {
            get {
                return ResourceManager.GetString("billed_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        public static string billing {
            get {
                return ResourceManager.GetString("billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Group.
        /// </summary>
        public static string billing_group {
            get {
                return ResourceManager.GetString("billing_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing increment.
        /// </summary>
        public static string billing_increment {
            get {
                return ResourceManager.GetString("billing_increment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Time Zone.
        /// </summary>
        public static string billing_timezone {
            get {
                return ResourceManager.GetString("billing_timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Balance on cancel.
        /// </summary>
        public static string cancelled_change_balance {
            get {
                return ResourceManager.GetString("cancelled_change_balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge balance.
        /// </summary>
        public static string charge_balance {
            get {
                return ResourceManager.GetString("charge_balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance charged via {0}.
        /// </summary>
        public static string charge_by {
            get {
                return ResourceManager.GetString("charge_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance transferred from Card: {0} to Account: {1}.
        /// </summary>
        public static string charge_by_calling_card {
            get {
                return ResourceManager.GetString("charge_by_calling_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit: {0} transferred from Card: {1} to Account: {2}.
        /// </summary>
        public static string charge_by_calling_card_log {
            get {
                return ResourceManager.GetString("charge_by_calling_card_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit: {0} charged via : {1} to Account: {2}.
        /// </summary>
        public static string charge_by_log {
            get {
                return ResourceManager.GetString("charge_by_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last charge.
        /// </summary>
        public static string charge_last {
            get {
                return ResourceManager.GetString("charge_last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert Charge.
        /// </summary>
        public static string charge_revert {
            get {
                return ResourceManager.GetString("charge_revert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheap.
        /// </summary>
        public static string cheap {
            get {
                return ResourceManager.GetString("cheap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a payment method and a desired amount.
        /// </summary>
        public static string choose_methode_amount {
            get {
                return ResourceManager.GetString("choose_methode_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission.
        /// </summary>
        public static string commission {
            get {
                return ResourceManager.GetString("commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reseller Commission.
        /// </summary>
        public static string commission_reseller {
            get {
                return ResourceManager.GetString("commission_reseller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Commission.
        /// </summary>
        public static string commission_vendor {
            get {
                return ResourceManager.GetString("commission_vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting credit.
        /// </summary>
        public static string creadit_starting {
            get {
                return ResourceManager.GetString("creadit_starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        public static string currencies {
            get {
                return ResourceManager.GetString("currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string currency {
            get {
                return ResourceManager.GetString("currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Identifier.
        /// </summary>
        public static string external_id {
            get {
                return ResourceManager.GetString("external_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to payment gateway.
        /// </summary>
        public static string gateway_connection_failed {
            get {
                return ResourceManager.GetString("gateway_connection_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment gateway response with error.
        /// </summary>
        public static string gateway_reports_error {
            get {
                return ResourceManager.GetString("gateway_reports_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway Transaction ID.
        /// </summary>
        public static string gateway_transaction_id {
            get {
                return ResourceManager.GetString("gateway_transaction_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway Transaction Data.
        /// </summary>
        public static string gatway_transaction_data {
            get {
                return ResourceManager.GetString("gatway_transaction_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holder.
        /// </summary>
        public static string holder {
            get {
                return ResourceManager.GetString("holder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN.
        /// </summary>
        public static string iban {
            get {
                return ResourceManager.GetString("iban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invoice.
        /// </summary>
        public static string invoice_download_filename {
            get {
                return ResourceManager.GetString("invoice_download_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice E-Mail.
        /// </summary>
        public static string invoice_email {
            get {
                return ResourceManager.GetString("invoice_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully hidden Invoice to Customer.
        /// </summary>
        public static string invoice_hide_success {
            get {
                return ResourceManager.GetString("invoice_hide_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find Invoice.
        /// </summary>
        public static string invoice_not_found {
            get {
                return ResourceManager.GetString("invoice_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully reset download count for Invoice.
        /// </summary>
        public static string invoice_reset_downloads_success {
            get {
                return ResourceManager.GetString("invoice_reset_downloads_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully changed to visible for Customer.
        /// </summary>
        public static string invoice_show_success {
            get {
                return ResourceManager.GetString("invoice_show_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully unhidden Invoice to Customer.
        /// </summary>
        public static string invoice_unhide_success {
            get {
                return ResourceManager.GetString("invoice_unhide_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices Total.
        /// </summary>
        public static string invoices_total {
            get {
                return ResourceManager.GetString("invoices_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itemized Statement Xed.
        /// </summary>
        public static string itemized_statement_xed {
            get {
                return ResourceManager.GetString("itemized_statement_xed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If activated, the last 3 digits of the called destination phone numbers will appear as XXX..
        /// </summary>
        public static string itemized_statement_xed_desc {
            get {
                return ResourceManager.GetString("itemized_statement_xed_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string paid {
            get {
                return ResourceManager.GetString("paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid on.
        /// </summary>
        public static string paid_on {
            get {
                return ResourceManager.GetString("paid_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string payment {
            get {
                return ResourceManager.GetString("payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Acknowledged By.
        /// </summary>
        public static string payment_ack_by {
            get {
                return ResourceManager.GetString("payment_ack_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment By.
        /// </summary>
        public static string payment_by {
            get {
                return ResourceManager.GetString("payment_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        public static string payment_methode {
            get {
                return ResourceManager.GetString("payment_methode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method could not be found.
        /// </summary>
        public static string payment_methode_not_found {
            get {
                return ResourceManager.GetString("payment_methode_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Methods.
        /// </summary>
        public static string payment_methodes {
            get {
                return ResourceManager.GetString("payment_methodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully charged balance.
        /// </summary>
        public static string payment_success {
            get {
                return ResourceManager.GetString("payment_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments.
        /// </summary>
        public static string payments {
            get {
                return ResourceManager.GetString("payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal.
        /// </summary>
        public static string paypal {
            get {
                return ResourceManager.GetString("paypal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal E-Mail.
        /// </summary>
        public static string paypal_email {
            get {
                return ResourceManager.GetString("paypal_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling-Card.
        /// </summary>
        public static string phonecard {
            get {
                return ResourceManager.GetString("phonecard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string rate {
            get {
                return ResourceManager.GetString("rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate / Min.
        /// </summary>
        public static string rate_per_min {
            get {
                return ResourceManager.GetString("rate_per_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reseller Rate.
        /// </summary>
        public static string rate_reseller {
            get {
                return ResourceManager.GetString("rate_reseller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Sheet.
        /// </summary>
        public static string rate_sheet {
            get {
                return ResourceManager.GetString("rate_sheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reseller Rate Sheet.
        /// </summary>
        public static string rate_sheet_reseller {
            get {
                return ResourceManager.GetString("rate_sheet_reseller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Rate Sheet.
        /// </summary>
        public static string rate_sheet_vendor {
            get {
                return ResourceManager.GetString("rate_sheet_vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Sheets.
        /// </summary>
        public static string rate_sheets {
            get {
                return ResourceManager.GetString("rate_sheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Rate.
        /// </summary>
        public static string rate_vendor {
            get {
                return ResourceManager.GetString("rate_vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rates.
        /// </summary>
        public static string rates {
            get {
                return ResourceManager.GetString("rates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rates E-Mail.
        /// </summary>
        public static string rates_email {
            get {
                return ResourceManager.GetString("rates_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One moment, your are redirected to &lt;strong&gt;{0}&lt;/strong&gt;.
        /// </summary>
        public static string redirect_to {
            get {
                return ResourceManager.GetString("redirect_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string reference {
            get {
                return ResourceManager.GetString("reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Number.
        /// </summary>
        public static string registration_number {
            get {
                return ResourceManager.GetString("registration_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remitter.
        /// </summary>
        public static string remittee {
            get {
                return ResourceManager.GetString("remittee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTN / ABA.
        /// </summary>
        public static string rtn {
            get {
                return ResourceManager.GetString("rtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFORT.
        /// </summary>
        public static string sofort {
            get {
                return ResourceManager.GetString("sofort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        public static string tax {
            get {
                return ResourceManager.GetString("tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Amount per Transaction.
        /// </summary>
        public static string transaction_amount_min {
            get {
                return ResourceManager.GetString("transaction_amount_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Transaction.
        /// </summary>
        public static string transaction_cancel {
            get {
                return ResourceManager.GetString("transaction_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot reactivate a deleted transaction. Restore the transaction first..
        /// </summary>
        public static string transaction_cancel_error_is_deleted {
            get {
                return ResourceManager.GetString("transaction_cancel_error_is_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction successfully cancelled.
        /// </summary>
        public static string transaction_cancel_success {
            get {
                return ResourceManager.GetString("transaction_cancel_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this transaction?.
        /// </summary>
        public static string transaction_delete_ask {
            get {
                return ResourceManager.GetString("transaction_delete_ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction must be cancelled before you can delete it..
        /// </summary>
        public static string transaction_delete_error_not_cancelled {
            get {
                return ResourceManager.GetString("transaction_delete_error_not_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction successfully deleted.
        /// </summary>
        public static string transaction_delete_success {
            get {
                return ResourceManager.GetString("transaction_delete_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction ID.
        /// </summary>
        public static string transaction_id {
            get {
                return ResourceManager.GetString("transaction_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction successfully reactivated.
        /// </summary>
        public static string transaction_reactivated_success {
            get {
                return ResourceManager.GetString("transaction_reactivated_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to restore this transaction?.
        /// </summary>
        public static string transaction_restore_ask {
            get {
                return ResourceManager.GetString("transaction_restore_ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction successfully restored.
        /// </summary>
        public static string transaction_restore_success {
            get {
                return ResourceManager.GetString("transaction_restore_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want do change the status of this transaction?.
        /// </summary>
        public static string transaction_status_ask {
            get {
                return ResourceManager.GetString("transaction_status_ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction status successfully updated.
        /// </summary>
        public static string transaction_status_success {
            get {
                return ResourceManager.GetString("transaction_status_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string transfer {
            get {
                return ResourceManager.GetString("transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Payments.
        /// </summary>
        public static string vendor_payments {
            get {
                return ResourceManager.GetString("vendor_payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} balance charge.
        /// </summary>
        public static string wire_reference_1 {
            get {
                return ResourceManager.GetString("wire_reference_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account {0}.
        /// </summary>
        public static string wire_reference_2 {
            get {
                return ResourceManager.GetString("wire_reference_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wire transfer.
        /// </summary>
        public static string wiretransfer {
            get {
                return ResourceManager.GetString("wiretransfer", resourceCulture);
            }
        }
    }
}
