//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiCo.Utilities.I18n {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Date {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Date() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiCo.Utilities.I18n.Date", typeof(Date).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string april {
            get {
                return ResourceManager.GetString("april", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apr.
        /// </summary>
        public static string april_short {
            get {
                return ResourceManager.GetString("april_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string august {
            get {
                return ResourceManager.GetString("august", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aug.
        /// </summary>
        public static string august_short {
            get {
                return ResourceManager.GetString("august_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All dates and times are given in UTC.
        /// </summary>
        public static string date_all_utc {
            get {
                return ResourceManager.GetString("date_all_utc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string date_end {
            get {
                return ResourceManager.GetString("date_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd.mm.yyyy.
        /// </summary>
        public static string date_format {
            get {
                return ResourceManager.GetString("date_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string date_start {
            get {
                return ResourceManager.GetString("date_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string day {
            get {
                return ResourceManager.GetString("day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        public static string day_short {
            get {
                return ResourceManager.GetString("day_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string december {
            get {
                return ResourceManager.GetString("december", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dec.
        /// </summary>
        public static string december_short {
            get {
                return ResourceManager.GetString("december_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string february {
            get {
                return ResourceManager.GetString("february", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feb.
        /// </summary>
        public static string february_short {
            get {
                return ResourceManager.GetString("february_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat.
        /// </summary>
        public static string flat {
            get {
                return ResourceManager.GetString("flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string friday {
            get {
                return ResourceManager.GetString("friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fri.
        /// </summary>
        public static string friday_short {
            get {
                return ResourceManager.GetString("friday_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string hour {
            get {
                return ResourceManager.GetString("hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        public static string hour_short {
            get {
                return ResourceManager.GetString("hour_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string january {
            get {
                return ResourceManager.GetString("january", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jan.
        /// </summary>
        public static string january_short {
            get {
                return ResourceManager.GetString("january_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string july {
            get {
                return ResourceManager.GetString("july", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jul.
        /// </summary>
        public static string july_short {
            get {
                return ResourceManager.GetString("july_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string june {
            get {
                return ResourceManager.GetString("june", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jun.
        /// </summary>
        public static string june_short {
            get {
                return ResourceManager.GetString("june_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string march {
            get {
                return ResourceManager.GetString("march", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mar.
        /// </summary>
        public static string march_short {
            get {
                return ResourceManager.GetString("march_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string may {
            get {
                return ResourceManager.GetString("may", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string may_short {
            get {
                return ResourceManager.GetString("may_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string minute {
            get {
                return ResourceManager.GetString("minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string minute_short {
            get {
                return ResourceManager.GetString("minute_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string monday {
            get {
                return ResourceManager.GetString("monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon.
        /// </summary>
        public static string monday_short {
            get {
                return ResourceManager.GetString("monday_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string month {
            get {
                return ResourceManager.GetString("month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        public static string months {
            get {
                return ResourceManager.GetString("months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string november {
            get {
                return ResourceManager.GetString("november", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nov.
        /// </summary>
        public static string november_short {
            get {
                return ResourceManager.GetString("november_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string october {
            get {
                return ResourceManager.GetString("october", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oct.
        /// </summary>
        public static string october_short {
            get {
                return ResourceManager.GetString("october_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off Peak.
        /// </summary>
        public static string offpeak {
            get {
                return ResourceManager.GetString("offpeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak.
        /// </summary>
        public static string peak {
            get {
                return ResourceManager.GetString("peak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string saturday {
            get {
                return ResourceManager.GetString("saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        public static string saturday_short {
            get {
                return ResourceManager.GetString("saturday_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        public static string second {
            get {
                return ResourceManager.GetString("second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string second_short {
            get {
                return ResourceManager.GetString("second_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        public static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string september {
            get {
                return ResourceManager.GetString("september", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sep.
        /// </summary>
        public static string september_short {
            get {
                return ResourceManager.GetString("september_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string sunday {
            get {
                return ResourceManager.GetString("sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        public static string sunday_short {
            get {
                return ResourceManager.GetString("sunday_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string thursday {
            get {
                return ResourceManager.GetString("thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thurs..
        /// </summary>
        public static string thursday_short {
            get {
                return ResourceManager.GetString("thursday_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Till.
        /// </summary>
        public static string till {
            get {
                return ResourceManager.GetString("till", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ringtime.
        /// </summary>
        public static string time_ring {
            get {
                return ResourceManager.GetString("time_ring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talktime.
        /// </summary>
        public static string time_talk {
            get {
                return ResourceManager.GetString("time_talk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yate Time.
        /// </summary>
        public static string time_yate {
            get {
                return ResourceManager.GetString("time_yate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeband.
        /// </summary>
        public static string timeband {
            get {
                return ResourceManager.GetString("timeband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timebands.
        /// </summary>
        public static string timebands {
            get {
                return ResourceManager.GetString("timebands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone.
        /// </summary>
        public static string timezone {
            get {
                return ResourceManager.GetString("timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezones.
        /// </summary>
        public static string timezones {
            get {
                return ResourceManager.GetString("timezones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string today {
            get {
                return ResourceManager.GetString("today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string tuesday {
            get {
                return ResourceManager.GetString("tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tues.
        /// </summary>
        public static string tuesday_short {
            get {
                return ResourceManager.GetString("tuesday_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string wednesday {
            get {
                return ResourceManager.GetString("wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed.
        /// </summary>
        public static string wednesday_short {
            get {
                return ResourceManager.GetString("wednesday_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string week {
            get {
                return ResourceManager.GetString("week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekend.
        /// </summary>
        public static string weekend {
            get {
                return ResourceManager.GetString("weekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weeks.
        /// </summary>
        public static string weeks {
            get {
                return ResourceManager.GetString("weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string year {
            get {
                return ResourceManager.GetString("year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        public static string years {
            get {
                return ResourceManager.GetString("years", resourceCulture);
            }
        }
    }
}
