//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiCo.Utilities.I18n {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Error {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Error() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiCo.Utilities.I18n.Error", typeof(Error).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        public static string access_denied {
            get {
                return ResourceManager.GetString("access_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account is already activated.
        /// </summary>
        public static string account_active_already {
            get {
                return ResourceManager.GetString("account_active_already", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account was locked, please contact our support team..
        /// </summary>
        public static string account_locked {
            get {
                return ResourceManager.GetString("account_locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given amount is to high.
        /// </summary>
        public static string amount_big {
            get {
                return ResourceManager.GetString("amount_big", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given amount is to small.
        /// </summary>
        public static string amount_small {
            get {
                return ResourceManager.GetString("amount_small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is unbooked balance for this account. Balance:.
        /// </summary>
        public static string balance_left {
            get {
                return ResourceManager.GetString("balance_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a cancel reason.
        /// </summary>
        public static string cancel_reason_empty {
            get {
                return ResourceManager.GetString("cancel_reason_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card is expired.
        /// </summary>
        public static string card_expired {
            get {
                return ResourceManager.GetString("card_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load chart..
        /// </summary>
        public static string chart_loading {
            get {
                return ResourceManager.GetString("chart_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the form..
        /// </summary>
        public static string check_form {
            get {
                return ResourceManager.GetString("check_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Code.
        /// </summary>
        public static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find country.
        /// </summary>
        public static string country_not_found {
            get {
                return ResourceManager.GetString("country_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No country set.
        /// </summary>
        public static string country_not_set {
            get {
                return ResourceManager.GetString("country_not_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dailcode could not be find.
        /// </summary>
        public static string dailcode_not_found {
            get {
                return ResourceManager.GetString("dailcode_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input data is outdated, syncing data..
        /// </summary>
        public static string data_is_not_sync {
            get {
                return ResourceManager.GetString("data_is_not_sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to database.
        /// </summary>
        public static string database_connect {
            get {
                return ResourceManager.GetString("database_connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date cannot be earlier start date.
        /// </summary>
        public static string date_end {
            get {
                return ResourceManager.GetString("date_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date cannot be later then end date.
        /// </summary>
        public static string date_start {
            get {
                return ResourceManager.GetString("date_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete item.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denied.
        /// </summary>
        public static string denied {
            get {
                return ResourceManager.GetString("denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny.
        /// </summary>
        public static string deny {
            get {
                return ResourceManager.GetString("deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency:.
        /// </summary>
        public static string dependency {
            get {
                return ResourceManager.GetString("dependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency with account:.
        /// </summary>
        public static string dependency_account {
            get {
                return ResourceManager.GetString("dependency_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency with context:.
        /// </summary>
        public static string dependency_context {
            get {
                return ResourceManager.GetString("dependency_context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency with ip:.
        /// </summary>
        public static string dependency_ip {
            get {
                return ResourceManager.GetString("dependency_ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency with node:.
        /// </summary>
        public static string dependency_node {
            get {
                return ResourceManager.GetString("dependency_node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency with phonebook:.
        /// </summary>
        public static string dependency_phonebook {
            get {
                return ResourceManager.GetString("dependency_phonebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency with Registered Numbers:.
        /// </summary>
        public static string dependency_registeredNumber {
            get {
                return ResourceManager.GetString("dependency_registeredNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency with route:.
        /// </summary>
        public static string dependency_route {
            get {
                return ResourceManager.GetString("dependency_route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This domain is blacklisted!.
        /// </summary>
        public static string domain_blacklisted {
            get {
                return ResourceManager.GetString("domain_blacklisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item already exists, could not create same item again..
        /// </summary>
        public static string duplicate_item {
            get {
                return ResourceManager.GetString("duplicate_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On error occurred. Could not send confirmation key..
        /// </summary>
        public static string email_activation_send_fail {
            get {
                return ResourceManager.GetString("email_activation_send_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not send E-Mail.
        /// </summary>
        public static string email_send {
            get {
                return ResourceManager.GetString("email_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum type not found.
        /// </summary>
        public static string enum_not_found {
            get {
                return ResourceManager.GetString("enum_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error list.
        /// </summary>
        public static string error_list {
            get {
                return ResourceManager.GetString("error_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        public static string exception {
            get {
                return ResourceManager.GetString("exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit logs for more information.
        /// </summary>
        public static string goto_log {
            get {
                return ResourceManager.GetString("goto_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource could not be found..
        /// </summary>
        public static string http_4xx {
            get {
                return ResourceManager.GetString("http_4xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string http_5xx {
            get {
                return ResourceManager.GetString("http_5xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter some information.
        /// </summary>
        public static string info_empty {
            get {
                return ResourceManager.GetString("info_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is not valid, please edit.
        /// </summary>
        public static string input_invalid {
            get {
                return ResourceManager.GetString("input_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save changes.
        /// </summary>
        public static string internal_db_save_error {
            get {
                return ResourceManager.GetString("internal_db_save_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your have been blocked.
        /// </summary>
        public static string ip_blocked {
            get {
                return ResourceManager.GetString("ip_blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given IP address is wrong.
        /// </summary>
        public static string ip_invalid {
            get {
                return ResourceManager.GetString("ip_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given network is too big.
        /// </summary>
        public static string ip_network_big {
            get {
                return ResourceManager.GetString("ip_network_big", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only a single IP address is valid, not a network.
        /// </summary>
        public static string ip_no_network {
            get {
                return ResourceManager.GetString("ip_no_network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address must be set.
        /// </summary>
        public static string ip_unset {
            get {
                return ResourceManager.GetString("ip_unset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the maximum number of activation requests. If you need more activation request please contact our support..
        /// </summary>
        public static string key_max_request {
            get {
                return ResourceManager.GetString("key_max_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given activation key is wrong.
        /// </summary>
        public static string key_wrong {
            get {
                return ResourceManager.GetString("key_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No language set.
        /// </summary>
        public static string language_missing {
            get {
                return ResourceManager.GetString("language_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string not_found {
            get {
                return ResourceManager.GetString("not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found.
        /// </summary>
        public static string not_found_item_name {
            get {
                return ResourceManager.GetString("not_found_item_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This phone number is blacklisted!.
        /// </summary>
        public static string number_blacklisted {
            get {
                return ResourceManager.GetString("number_blacklisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given value is not a valid phone number..
        /// </summary>
        public static string number_phone {
            get {
                return ResourceManager.GetString("number_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter is missing or empty.
        /// </summary>
        public static string parameter_empty {
            get {
                return ResourceManager.GetString("parameter_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered PIN is wrong.
        /// </summary>
        public static string pin_wrong {
            get {
                return ResourceManager.GetString("pin_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix must start with digits and may end with &apos;#&apos;, e.g. 1234#.
        /// </summary>
        public static string prefix_voip {
            get {
                return ResourceManager.GetString("prefix_voip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a reason.
        /// </summary>
        public static string reason_empty {
            get {
                return ResourceManager.GetString("reason_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item is required.
        /// </summary>
        public static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings could not be saved..
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry an error occurred. We are informed about that..
        /// </summary>
        public static string sorry {
            get {
                return ResourceManager.GetString("sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All updates have failed.
        /// </summary>
        public static string tasks_all {
            get {
                return ResourceManager.GetString("tasks_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some updates have failed.
        /// </summary>
        public static string tasks_partial {
            get {
                return ResourceManager.GetString("tasks_partial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} out of {1} updates failed.
        /// </summary>
        public static string tasks_partial_count {
            get {
                return ResourceManager.GetString("tasks_partial_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session timed out.
        /// </summary>
        public static string timed_out {
            get {
                return ResourceManager.GetString("timed_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction cancelled.
        /// </summary>
        public static string transaction_cancelled {
            get {
                return ResourceManager.GetString("transaction_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find transaction.
        /// </summary>
        public static string transaction_not_found {
            get {
                return ResourceManager.GetString("transaction_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred..
        /// </summary>
        public static string unknow {
            get {
                return ResourceManager.GetString("unknow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string unknown {
            get {
                return ResourceManager.GetString("unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed.
        /// </summary>
        public static string validation {
            get {
                return ResourceManager.GetString("validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is out of range.
        /// </summary>
        public static string value_out_range {
            get {
                return ResourceManager.GetString("value_out_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The warning limit will never be reached, because the main limit is smaller..
        /// </summary>
        public static string wran_smaller_limit {
            get {
                return ResourceManager.GetString("wran_smaller_limit", resourceCulture);
            }
        }
    }
}
