//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiCo.Utilities.I18n {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiCo.Utilities.I18n.Messages", typeof(Messages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update account information.
        /// </summary>
        public static string account_update {
            get {
                return ResourceManager.GetString("account_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update account information.
        /// </summary>
        public static string account_update_error {
            get {
                return ResourceManager.GetString("account_update_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account information updated successfully.
        /// </summary>
        public static string account_update_success {
            get {
                return ResourceManager.GetString("account_update_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New confirmation key send..
        /// </summary>
        public static string activation_key_send {
            get {
                return ResourceManager.GetString("activation_key_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction was canceled by user..
        /// </summary>
        public static string canceled_by_user {
            get {
                return ResourceManager.GetString("canceled_by_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your e-mail address is already activated.
        /// </summary>
        public static string email_activated_already {
            get {
                return ResourceManager.GetString("email_activated_already", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail Address successfully activated.
        /// </summary>
        public static string email_activated_success {
            get {
                return ResourceManager.GetString("email_activated_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail address successfully updated. Confirmation key send to new e-mail address..
        /// </summary>
        public static string email_activation_send {
            get {
                return ResourceManager.GetString("email_activation_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New E-Mail Address Confirmation Key.
        /// </summary>
        public static string email_new_confirmation_key {
            get {
                return ResourceManager.GetString("email_new_confirmation_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To enable your new e-mail address please enter the validation code.
        /// </summary>
        public static string email_new_validate_desc {
            get {
                return ResourceManager.GetString("email_new_validate_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail successfully send.
        /// </summary>
        public static string email_send {
            get {
                return ResourceManager.GetString("email_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail Address update reverted successfully.
        /// </summary>
        public static string email_update_revert {
            get {
                return ResourceManager.GetString("email_update_revert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given E-Mail Address is already used by an other account..
        /// </summary>
        public static string email_used_by_other {
            get {
                return ResourceManager.GetString("email_used_by_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate E-Mail Address.
        /// </summary>
        public static string email_validate {
            get {
                return ResourceManager.GetString("email_validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your E-Mail address is not validated yet. Please validate it now.
        /// </summary>
        public static string email_validate_desc {
            get {
                return ResourceManager.GetString("email_validate_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate new captcha image.
        /// </summary>
        public static string generate_captcha {
            get {
                return ResourceManager.GetString("generate_captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has General Business Terms Accepted.
        /// </summary>
        public static string has_general_business_terms_accepted {
            get {
                return ResourceManager.GetString("has_general_business_terms_accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item activated successfully.
        /// </summary>
        public static string item_activate_done {
            get {
                return ResourceManager.GetString("item_activate_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not activate item.
        /// </summary>
        public static string item_activate_error {
            get {
                return ResourceManager.GetString("item_activate_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item added successfully.
        /// </summary>
        public static string item_add_success {
            get {
                return ResourceManager.GetString("item_add_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this?.
        /// </summary>
        public static string item_delete_ask {
            get {
                return ResourceManager.GetString("item_delete_ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item successfully deleted.
        /// </summary>
        public static string item_delete_done {
            get {
                return ResourceManager.GetString("item_delete_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete item.
        /// </summary>
        public static string item_delete_fail {
            get {
                return ResourceManager.GetString("item_delete_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item successfully disabled.
        /// </summary>
        public static string item_disable_success {
            get {
                return ResourceManager.GetString("item_disable_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item successfully enabled.
        /// </summary>
        public static string item_enabled_success {
            get {
                return ResourceManager.GetString("item_enabled_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item loaded successfully.
        /// </summary>
        public static string item_load_success {
            get {
                return ResourceManager.GetString("item_load_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item could not be found..
        /// </summary>
        public static string item_not_found {
            get {
                return ResourceManager.GetString("item_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item successfully restored.
        /// </summary>
        public static string item_restore_success {
            get {
                return ResourceManager.GetString("item_restore_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item successfully updated.
        /// </summary>
        public static string item_update_success {
            get {
                return ResourceManager.GetString("item_update_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to mark this as active?.
        /// </summary>
        public static string mark_active_ask {
            get {
                return ResourceManager.GetString("mark_active_ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item successfully marked as active.
        /// </summary>
        public static string mark_active_done {
            get {
                return ResourceManager.GetString("mark_active_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not mark this as active.
        /// </summary>
        public static string mark_active_error {
            get {
                return ResourceManager.GetString("mark_active_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to mark this as deleted?.
        /// </summary>
        public static string mark_delete_ask {
            get {
                return ResourceManager.GetString("mark_delete_ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item successfully marked as deleted.
        /// </summary>
        public static string mark_delete_done {
            get {
                return ResourceManager.GetString("mark_delete_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not mark this as deleted.
        /// </summary>
        public static string mark_delete_error {
            get {
                return ResourceManager.GetString("mark_delete_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to ping this IP address?.
        /// </summary>
        public static string ping_ask {
            get {
                return ResourceManager.GetString("ping_ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address successfully pinged.
        /// </summary>
        public static string ping_done {
            get {
                return ResourceManager.GetString("ping_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping timed out may be ICMP packages are drop by a firewall.
        /// </summary>
        public static string ping_error_timeout {
            get {
                return ResourceManager.GetString("ping_error_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing your login....
        /// </summary>
        public static string processing_your_login {
            get {
                return ResourceManager.GetString("processing_your_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not send request.
        /// </summary>
        public static string request_send_error {
            get {
                return ResourceManager.GetString("request_send_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log on failed. Please try again..
        /// </summary>
        public static string sign_in_failed {
            get {
                return ResourceManager.GetString("sign_in_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read the &lt;a href=&quot;{0}&quot; target=&quot;_blank&quot;&gt;Service Terms&lt;/a&gt; and I do accept them..
        /// </summary>
        public static string terms_acceppt_question {
            get {
                return ResourceManager.GetString("terms_acceppt_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave notes which could be useful in case of failure.
        /// </summary>
        public static string ticket_notes_help {
            get {
                return ResourceManager.GetString("ticket_notes_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket successfully send..
        /// </summary>
        public static string ticket_send_done {
            get {
                return ResourceManager.GetString("ticket_send_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not send ticket please try again.
        /// </summary>
        public static string ticket_send_fail {
            get {
                return ResourceManager.GetString("ticket_send_fail", resourceCulture);
            }
        }
    }
}
