//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiCo.Utilities.I18n {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Password {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        public Password() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiCo.Utilities.I18n.Password", typeof(Password).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Password is blacklisted, please choose a new one..
        /// </summary>
        public static string blacklist {
            get {
                return ResourceManager.GetString("blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Change Password.
        /// </summary>
        public static string change {
            get {
                return ResourceManager.GetString("change", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Your password was not accepted. Please try again..
        /// </summary>
        public static string change_error {
            get {
                return ResourceManager.GetString("change_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Your password was not accepted. You need 8 characters in upper and lower case and special characters. Please try again..
        /// </summary>
        public static string change_error_strong {
            get {
                return ResourceManager.GetString("change_error_strong", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Fields &apos;New Password&apos; and &apos;Confirm Password&apos; do not match..
        /// </summary>
        public static string confirm_wrong {
            get {
                return ResourceManager.GetString("confirm_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Password must contain at least one &lt;b&gt;lower and &lt;/b&gt; one &lt;b&gt;upper&lt;/b&gt; character.
        /// </summary>
        public static string contain_lower_upper {
            get {
                return ResourceManager.GetString("contain_lower_upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Password must contain one &lt;b&gt;numerical&lt;/b&gt; character.
        /// </summary>
        public static string contain_number {
            get {
                return ResourceManager.GetString("contain_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Password must contain one &lt;b&gt;numerical and/or &lt;/b&gt; one &lt;b&gt;special&lt;/b&gt; character.
        /// </summary>
        public static string contain_number_special {
            get {
                return ResourceManager.GetString("contain_number_special", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Password must contain one &lt;b&gt;special&lt;/b&gt; character.
        /// </summary>
        public static string contain_special {
            get {
                return ResourceManager.GetString("contain_special", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Current Password.
        /// </summary>
        public static string current {
            get {
                return ResourceManager.GetString("current", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You must enter your current Password.
        /// </summary>
        public static string current_requiered {
            get {
                return ResourceManager.GetString("current_requiered", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Saturday1.
        /// </summary>
        public static string example1 {
            get {
                return ResourceManager.GetString("example1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to IloveDonuts$7.
        /// </summary>
        public static string example2 {
            get {
                return ResourceManager.GetString("example2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 2Weeksvacation.
        /// </summary>
        public static string example3 {
            get {
                return ResourceManager.GetString("example3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string forgot {
            get {
                return ResourceManager.GetString("forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Generate New Password.
        /// </summary>
        public static string generate {
            get {
                return ResourceManager.GetString("generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Generate New PIN.
        /// </summary>
        public static string generate_pin {
            get {
                return ResourceManager.GetString("generate_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Send Activation key.
        /// </summary>
        public static string key_send {
            get {
                return ResourceManager.GetString("key_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Password must be at least &lt;b&gt;6&lt;/b&gt; characters long.
        /// </summary>
        public static string length_6 {
            get {
                return ResourceManager.GetString("length_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Password must be at least &lt;b&gt;8&lt;/b&gt; characters long.
        /// </summary>
        public static string length_8 {
            get {
                return ResourceManager.GetString("length_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to New Password.
        /// </summary>
        public static string new_n {
            get {
                return ResourceManager.GetString("new_n", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to New password can not be empty.
        /// </summary>
        public static string new_reqiered {
            get {
                return ResourceManager.GetString("new_reqiered", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to We have generated a new Password and send it to you via {0}. This can take a moment..
        /// </summary>
        public static string new_send_via {
            get {
                return ResourceManager.GetString("new_send_via", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to New password is not complex enough.
        /// </summary>
        public static string not_complex {
            get {
                return ResourceManager.GetString("not_complex", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The confirmed password differs from the new one..
        /// </summary>
        public static string not_equal {
            get {
                return ResourceManager.GetString("not_equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Password Policy.
        /// </summary>
        public static string password_policy {
            get {
                return ResourceManager.GetString("password_policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Examples: Saturday1, IloveDonuts$7, 2Weeksvacation.
        /// </summary>
        public static string password_sample_easy {
            get {
                return ResourceManager.GetString("password_sample_easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Password reset.
        /// </summary>
        public static string reset_success {
            get {
                return ResourceManager.GetString("reset_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to New password set successfully..
        /// </summary>
        public static string set_success {
            get {
                return ResourceManager.GetString("set_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to This password is to short..
        /// </summary>
        public static string to_short {
            get {
                return ResourceManager.GetString("to_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to New password was one of the last 5 used. Please use a different one..
        /// </summary>
        public static string used {
            get {
                return ResourceManager.GetString("used", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Password is wrong.
        /// </summary>
        public static string wrong {
            get {
                return ResourceManager.GetString("wrong", resourceCulture);
            }
        }
    }
}
