//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiCo.Utilities.I18n {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Validation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        public Validation() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiCo.Utilities.I18n.Validation", typeof(Validation).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Input must contain one lowercase character.
        /// </summary>
        public static string any_lowercase {
            get {
                return ResourceManager.GetString("any_lowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Input must contain one special or numeric character.
        /// </summary>
        public static string any_special_number {
            get {
                return ResourceManager.GetString("any_special_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Input must contain one uppercase character.
        /// </summary>
        public static string any_upercase {
            get {
                return ResourceManager.GetString("any_upercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value is not a valid CIDR subnet.
        /// </summary>
        public static string cdir_wrong {
            get {
                return ResourceManager.GetString("cdir_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please enter a valid credit card number..
        /// </summary>
        public static string creditcard {
            get {
                return ResourceManager.GetString("creditcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please enter a valid date..
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please enter a valid date (ISO)..
        /// </summary>
        public static string date_iso {
            get {
                return ResourceManager.GetString("date_iso", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please enter only digits..
        /// </summary>
        public static string digits {
            get {
                return ResourceManager.GetString("digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please enter the same value again..
        /// </summary>
        public static string equal_to {
            get {
                return ResourceManager.GetString("equal_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please enter a value with a valid extension..
        /// </summary>
        public static string file_extension {
            get {
                return ResourceManager.GetString("file_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please check your selection..
        /// </summary>
        public static string invalid_selection {
            get {
                return ResourceManager.GetString("invalid_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to This is not a valid IPv4 address with a netmask, e.g. 199.29.5.31/32.
        /// </summary>
        public static string ipv4_address_netmask_invalid {
            get {
                return ResourceManager.GetString("ipv4_address_netmask_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid IPv4/IPv6 address.
        /// </summary>
        public static string ipv4_ipv6_address_invalid {
            get {
                return ResourceManager.GetString("ipv4_ipv6_address_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid IPv4/IPv6 address or hostname.
        /// </summary>
        public static string ipv4_ipv6_hostname_address_invalid {
            get {
                return ResourceManager.GetString("ipv4_ipv6_hostname_address_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please enter a value less than or equal to {0}..
        /// </summary>
        public static string max {
            get {
                return ResourceManager.GetString("max", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please enter no more than {1} characters..
        /// </summary>
        public static string max_lenght {
            get {
                return ResourceManager.GetString("max_lenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please enter a value greater than or equal to {0}..
        /// </summary>
        public static string min {
            get {
                return ResourceManager.GetString("min", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please enter at least {1} characters..
        /// </summary>
        public static string min_lenght {
            get {
                return ResourceManager.GetString("min_lenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please enter only numbers..
        /// </summary>
        public static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Phone numbers can only contain digits, except a leading &apos;+&apos;.
        /// </summary>
        public static string phone_digits {
            get {
                return ResourceManager.GetString("phone_digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to This Phone number is invalid.
        /// </summary>
        public static string phone_inavlid {
            get {
                return ResourceManager.GetString("phone_inavlid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to International phone numbers start either with &apos;+&apos;, &apos;00&apos; or any other digit except a single &apos;0&apos;.
        /// </summary>
        public static string phone_international {
            get {
                return ResourceManager.GetString("phone_international", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Phone numbers starting with &apos;+&apos; can not have &apos;0&apos; as second digit.
        /// </summary>
        public static string phone_plus_zero {
            get {
                return ResourceManager.GetString("phone_plus_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please insert a positive value..
        /// </summary>
        public static string positive_value {
            get {
                return ResourceManager.GetString("positive_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A prefix can only have numbers, and optional a &apos;#&apos; at the end.
        /// </summary>
        public static string prefix_invalid {
            get {
                return ResourceManager.GetString("prefix_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please enter a value between {0} and {1}..
        /// </summary>
        public static string range {
            get {
                return ResourceManager.GetString("range", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please enter a value between {0} and {1} characters long..
        /// </summary>
        public static string range_lenght {
            get {
                return ResourceManager.GetString("range_lenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Regular Expression is invalid..
        /// </summary>
        public static string regular_expression_invalid {
            get {
                return ResourceManager.GetString("regular_expression_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please fix this field..
        /// </summary>
        public static string remote {
            get {
                return ResourceManager.GetString("remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to This filed is required..
        /// </summary>
        public static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The field {0} must be active..
        /// </summary>
        public static string required_true_for {
            get {
                return ResourceManager.GetString("required_true_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please enter a valid URL..
        /// </summary>
        public static string url {
            get {
                return ResourceManager.GetString("url", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Valid.
        /// </summary>
        public static string valid {
            get {
                return ResourceManager.GetString("valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Valid from.
        /// </summary>
        public static string valid_from {
            get {
                return ResourceManager.GetString("valid_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Valid until.
        /// </summary>
        public static string valid_till {
            get {
                return ResourceManager.GetString("valid_till", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Validated.
        /// </summary>
        public static string validated {
            get {
                return ResourceManager.GetString("validated", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Property: &lt;strong&gt;{0}&lt;/strong&gt;.
        /// </summary>
        public static string validation_property_msg {
            get {
                return ResourceManager.GetString("validation_property_msg", resourceCulture);
            }
        }
    }
}
